#!/usr/bin/env bash

if [ -z "$(find $XENV_ROOT/envs -maxdepth 1 | tail -n +2)" ]; then
  return
fi


for f in "$XENV_ROOT/envs/"*; do
  if [ -e "$f" ]; then
    env_name="${f##*/}"
    env_var="$(echo $env_name | tr '[a-z]' '[A-Z]')_ROOT"
    env_var_value="$(eval echo \$$env_var)"
    eval export "$env_var"="$XENV_ROOT/envs/$env_name"
    if [[ ! ":$PATH:" == *"$XENV_ROOT/envs/$env_name/bin"* ]]; then
      export PATH="$XENV_ROOT/envs/$env_name/bin:$PATH"
    fi
    eval "$($env_name init - $SHELL)"
  fi
done
