#!/usr/bin/env bash

# Desc: Install an env or a plugin

shopt -s nullglob

opt_list=false
opt_local=false
opt_force=false
opt_plugin=false

ENVS_DIR="$XENV_ROOT/share/xenv-envs"
PLUGINS_DIR="$XENV_ROOT/share/xenv-plugins"

usage() {
  echo "Usage:"
  echo "  xenv install [-f] <env>"
  echo "  xenv install -p <env> <plugin>"
  echo "  xenv install [-p] -l"
  echo "  xenv install [-p] -L"
  exit 1
}

parse_raw() {
  if [ -n "${ENV_NAME+x}" ]; then
    if $opt_plugin && [ -z "${PLUGIN_NAME+x}" ]; then
      PLUGIN_NAME="$1"
    else
      usage
    fi
  else
    ENV_NAME="$1"
  fi
}

parse_options() {
  while [ ! "$#" = "0" ]; do
    case "$1" in
      -l|--list)
        opt_list=true ;;
      -L|--local)
        opt_local=true ;;
      -f|--force)
        opt_force=true ;;
      -p|--plugin)
        opt_plugin=true ;;
      *)
        parse_raw "$1" ;;
    esac
    shift
  done
}

install_env() {
  local env_name="$1"
  
  if [ -e "$XENV_ROOT/envs/$env_name" ]; then
    $opt_force || exit
  fi
  
  if [ ! -e "$ENVS_DIR/$env_name" ]; then
    echo "Unknown env $env_name"
    exit 1
  fi

  read_line GIT_URL "$ENVS_DIR/$env_name"
  git clone "$GIT_URL" "$XENV_ROOT/envs/$env_name"

  echo "$env_name was installed."
}

install_plugin() {
  local env_name="$1"
  local plugin_name="$2"

  if [ ! -e "$XENV_ROOT/envs/$env_name" ]; then
    echo "$env_name is not installed"
    exit 1
  fi

  if [ ! -e "$PLUGINS_DIR/$env_name/$plugin_name" ]; then
    echo "Unknown plugin $plugin_name"
    exit 1
  fi

  read_line GIT_URL "$PLUGINS_DIR/$env_name/$plugin_name"
  mkdir -p "$XENV_ROOT/envs/$env_name/plugins"
  git clone "$GIT_URL" "$XENV_ROOT/envs/$env_name/plugins/$plugin_name"

  echo "$plugin_name was installed"
}

parse_options "$@"

if $opt_list; then
  for f in "$ENVS_DIR/"*; do
    env_name="${f##*/}"
    if $opt_plugin; then
      for g in "$PLUGINS_DIR/$env_name/"*; do
        plugin_name="${g##*/}"
        echo "  $env_name/$plugin_name"
      done
    else
      echo "  $env_name"
    fi
  done
  exit
fi

if $opt_local; then
  for f in "$XENV_ROOT/envs/"*; do
    env_name="${f##*/}"
    if [ ! -e "$ENVS_DIR/$env_name" ]; then
      continue
    fi
    if $opt_plugin; then
      for g in "$XENV_ROOT/envs/$env_name/plugins/"*; do
        plugin_name="${g##*/}"
        if [ ! -e "$PLUGINS_DIR/$env_name/$plugin_name" ]; then
          continue
        fi
        echo "  $env_name/$plugin_name"
      done
    else
      echo "  $env_name"
    fi
  done
  exit
fi

if [ -z "${ENV_NAME+x}" ]; then
  usage
fi

if $opt_plugin; then
  if [ -z "${PLUGIN_NAME+x}" ]; then
    usage
  fi
  install_plugin "$ENV_NAME" "$PLUGIN_NAME"
else
  install_env "$ENV_NAME"
fi

